<a href="https://colab.research.google.com/github/dashakucheyeva/Course-Neural-Networks-and-Computer-Vision-/blob/main/step_1_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
# torch.zeros([3, 4])
# torch.ones([3, 4, 3]) #3 матрицы из единиц размерности [3, 4]

x = torch.Tensor([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# x.size()
# x.shape #то же самое, что и size
# x[1]
# x[0, 2] #3 элемент в 1 строке
# x[:, 0] #1 столбец
# x + 10
# x**2 #все элементы в квадрате

y = torch.Tensor([[12, 11, 10, 9], [8, 7, 6, 5], [4, 3, 2, 1]])

# x + y
# x * y
# x / y
# x % y #остаток от деления x на y
# torch.exp(x)
# torch.log(x)
# torch.sin(x)
# x > 3 #логическая операция
# mask = x > 3
# x[mask] #остаются только элементы с True/1
# x[x > 3] #то же самое без лишней переменной mask

y = x #это не копирование. На объект x начинает ссылаться и y
y[0, 0] = 999
print(x)
print(y)

x = torch.Tensor([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

y = x.clone() #копирование
y[0, 0] = 999
print(x)
print(y)

x.dtype #узнать тип данных тензора

x = x.double()
print(x)
x = x.int()
print(x)
x = x.float()
print(x)

tensor([[999.,   2.,   3.,   4.],
        [  5.,   6.,   7.,   8.],
        [  9.,  10.,  11.,  12.]])
tensor([[999.,   2.,   3.,   4.],
        [  5.,   6.,   7.,   8.],
        [  9.,  10.,  11.,  12.]])
tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])
tensor([[999.,   2.,   3.,   4.],
        [  5.,   6.,   7.,   8.],
        [  9.,  10.,  11.,  12.]])
tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]], dtype=torch.float64)
tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]], dtype=torch.int32)
tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])


In [ ]:
#функция, которая возвращает сумму (x.sum()) элементов
#тензора X, строго превышающих значение limit, которое
#является входным значением алгоритма

import torch

X = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
limit = int(input())

larger_than_limit_sum = (X[X > limit]).sum()

print(larger_than_limit_sum)

In [13]:
import numpy as np
x = np.array([[1, 2, 3, 4], [4, 3, 2, 1]])
x
x = torch.from_numpy(x) #превращаем numpy array в torch tensor
x
x = x.numpy() #обратно
x
x = torch.rand([2000, 3000]) #тензор со случайными числами
x

torch.cuda.is_available() #проверили, есть ли на машине GPU
#переводим на другой девайс
torch.device('cuda:0') #0 - индекс видеокарты, если их много

torch.device('cpu') #обратно на cpu

device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')

x_cuda = x.to(device)
x_cuda

%time y = (x - x + x * 10.0) ** 2
%time y_cuda = (x_cuda - x_cuda + x_cuda * 10.0) ** 2
#ускорение вычислений на GPU происходит только на довольно больших тензорах
#т.е. в случае [2, 3] GPU может работать медленнее,
#но в случае [2000, 3000] получаем профит в десятки раз

CPU times: user 14.3 ms, sys: 46.8 ms, total: 61.1 ms
Wall time: 61.5 ms
CPU times: user 1.31 ms, sys: 943 µs, total: 2.25 ms
Wall time: 1.74 ms
